version: "2.0"  
services:  
  influx:
    image: influxdb
    ports:
     - "8083:8083"
     - "8086:8086"
    environment:
     - INFLUXDB_USER=user
     - INFLUXDB_PASS=pass
     - INFLUXDB_NAME=dbname
     - PRE_CREATE_DB="dbname"
  grafana:
    image: grafana/grafana
    environment:
     - INFLUXDB_USER=user
     - INFLUXDB_PASS=pass
     - INFLUXDB_NAME=dbname
    ports:
     - "3000:3000"
    links:
     - influx
    depends_on:
     - influx